name = "crochetkit-ai"
pages_build_output_dir = "public"
compatibility_date = "2026-05-21"

[[d1_databases]]
binding = "CROCHETKIT_CONTACTS"
database_name = "crochetkit-contacts"
database_id = "14e4a012-f360-4121-aba0-7997918294bf"

[[d1_databases]]
binding = "CROCHETKIT_FEEDBACK"
database_name = "crochetkit-feedback"
database_id = "0a44109c-a11e-43d9-9861-0d96cdd62aea"

